# overrides application.yml for development environment

# connection to database and mail server
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars_world_db # name of the postgres db from docker-compose.yml
    username: username
    password: password
    # driver-class-name: org.postgresql.Driver # not needed since spring boot 2.0.0
  jpa:
    hibernate:
      ddl-auto: update # automatically updates the database schema on application startup
    show-sql: false # only true for debug purposes
    properties:
      hibernate:
        format_sql: true # formats sql queries (if show-sql is true)
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: giu
    password: giu
    properties:
      mail:
        smtp:
          trust: "*" # allow self-signed certificates
        auth: true # enable authentication
        starttls:
          enable: true # enable TLS (Transport Layer Security) encryption
        connectiontimeout: 5000 # max time to connect to the mail server
        timeout: 3000 # max time to wait for a response from the mail server
        writetimeout: 5000 # max time to write to the mail server